apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment
  namespace: ymohan3
  labels:
    app: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - image: ymohan3/getting-started:v2
        imagePullPolicy: Always
        name: poc
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "200Mi"
            cpu: "200m"
